package it.polimi.genomics.importer.FileDatabase

/**
  * Represents the current action to be done over a file.
  */
object FILE_STATUS extends Enumeration {
  type FILE_STATUS = Value
  val UPDATE = Value("UPDATE") //FILE HAS TO BE ADDED/UPDATED (EITHER TRANSFORMED OR LOADED)
  val OUTDATED = Value("OUTDATED") //LOCAL FILE EXISTS BUT IN ORIGIN DOES NOT EXIST ANYMORE HAS TO BE DELETED
  val NOTHING = Value("NOTHING") //FILE IS IN IT'S CORRECT STATE AND ALREADY PROCESSED. NOTHING TO BE DONE
  val COMPARE = Value("COMPARE") //TEMPORARY STATUS TO CHECK IF FILES HAVE BEEN REMOVED FROM THE SERVER.
  val FAILED = Value("FAILED") //AUXILIARY STATUS TO MARK THAT WHATEVER DONE AFTER CHECK IF UPDATE IS NOT DONE CORRECTLY
}
